Upgrade common-gradle-plugin to latest in order to stop uploading artifacts to Maven Central
blackducksoftware/blackduck-common pull request #425
Opened 2024-07-03 19:05 UTC by andrian-sevastyanov

Upgrade common-gradle-plugin to latest in order to stop uploading artifacts to Maven Central.

No evidence of recent blackduck-common usage has been discovered. If a customer reaches out about being unable to download artifacts, we can point them to our Artifactory.

2024-07-03 19:09 UTC, devmehtasynopsys approved these changes

2024-07-03 19:09 UTC, andrian-sevastyanov commented on EULA.txt
It is actually not clear to me why this file needs to be removed. I have done so based on @DanaMaxfield instructions in an email dated a couple of years ago. I wonder how this decision was made.

2024-07-09 13:41 UTC, DanaMaxfield requested changes
Check with Legal on the EULA, but otherwise this looks good.

2024-07-16 18:51 UTC, andrian-sevastyanov commented on EULA.txt
I chatted with @dmamidisynopsys and he confirmed that we have directive to remove these files from our repos.

2024-07-16 18:53 UTC, DanaMaxfield approved these changes

2024-07-16 18:56 UTC, merged